### ISSUE TITLE
A List/Database?

### ISSUE THREAD

**Issue by rberudev** [tchristofferson/StockMarketAPI#1]
Where can I find the list of stocks the plugin supports?

**Comment by tchristofferson** [comment]
**US:**
New York Stock Exchange (NYS)
NASDAQ (NAS)*
NYSE Arca (PSE)
Cboe BZX US Equities Exchange (BATS)
NYSE American (ASE)
**International (historical only):**
Toronto Stock Exchange (TSE)
London Stock Exchange (LON)
Korea Exchange (KRX)
Mexican Stock Exchange (MEX)
BSE Ltd. (BOM)
TSX Venture Exchange (TSX)
Tel Aviv Stock Exchange (TAE)
Euronext Paris (PAR)
XETRA (ETR)
Euronext Amsterdam (AMS)
Euronext Brussels (BRU)
Euronext Dublin (DUB)
Euronext Lisbon (LIS)
Abu Dhabi Securities Exchange (ADS)
