### ISSUE TITLE
[Suggestion] Add more data to events

### ISSUE THREAD

**Issue by johnyuki** [tchristofferson/StockMarketAPI#3]
For example, `PlayerSellSharesEvent` only really has `getPlayer()`, `getPrice()`, `getSymbol()`, and `getShares()`. It would be nice to be able to get the price that they brought the shares at so that the profit/loss could be calculated, the length of time that they owned the shares for, and any other data that is in the main plugin. Same goes for `PlayerSellAllSharesEvent`. Perhaps instead of returning the symbol, it could return some kind of "PlayerShare" object that includes the symbol, company name, price bought for, price sold for, etc, as fields, with `PlayerSellAllSharesEvent` returning an array of these PlayerShare objects instead of the two maps.

**Comment by tchristofferson** [comment]
This addition will be added in v1.7 which I plan on releasing Saturday 3/13/2021. The events will allow you to get an instance of IStock which has been updated to keep records of purchase history including the number of shares and at what price they were bought for.

**Comment by tchristofferson** [comment]
Added in v1.7 of the plugin (API version 1.2-SNAPSHOT)
